// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAndWatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyAndWatch'](arg1, arg2);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CandidateFromPath(arg1) {
  return window['go']['main']['App']['CandidateFromPath'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearMark() {
  return window['go']['main']['App']['ClearMark']();
}

export function DefaultConfig() {
  return window['go']['main']['App']['DefaultConfig']();
}

export function DetectSources(arg1) {
  return window['go']['main']['App']['DetectSources'](arg1);
}

export function GetEvent(arg1) {
  return window['go']['main']['App']['GetEvent'](arg1);
}

export function GetState(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetState'](arg1, arg2, arg3);
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function PickLogFile() {
  return window['go']['main']['App']['PickLogFile']();
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function SaveAndWatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAndWatch'](arg1, arg2, arg3);
}
