// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {detect} from '../models';

export function ApplyAndWatch(arg1:config.Config,arg2:boolean):Promise<void>;

export function Bootstrap():Promise<main.Bootstrap>;

export function CandidateFromPath(arg1:string):Promise<detect.Candidate>;

export function Clear():Promise<void>;

export function DefaultConfig():Promise<config.Config>;

export function DetectSources(arg1:string):Promise<Array<detect.Candidate>>;

export function GetEvent(arg1:string):Promise<main.EventDTO>;

export function GetState(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function NewProject():Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function PickLogFile():Promise<string>;

export function PickProjectDir():Promise<string>;

export function SaveAndWatch(arg1:string,arg2:config.Config,arg3:boolean):Promise<void>;
