// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAndWatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyAndWatch'](arg1, arg2);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CandidateFromPath(arg1) {
  return window['go']['main']['App']['CandidateFromPath'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearMark() {
  return window['go']['main']['App']['ClearMark']();
}

export function DefaultConfig() {
  return window['go']['main']['App']['DefaultConfig']();
}

export function DetectEditors() {
  return window['go']['main']['App']['DetectEditors']();
}

export function DetectSources(arg1) {
  return window['go']['main']['App']['DetectSources'](arg1);
}

export function Dismiss(arg1) {
  return window['go']['main']['App']['Dismiss'](arg1);
}

export function DismissMatching(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DismissMatching'](arg1, arg2, arg3, arg4);
}

export function FaultlineLogPath() {
  return window['go']['main']['App']['FaultlineLogPath']();
}

export function GetEvent(arg1) {
  return window['go']['main']['App']['GetEvent'](arg1);
}

export function GetState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetState'](arg1, arg2, arg3, arg4);
}

export function Mute(arg1, arg2) {
  return window['go']['main']['App']['Mute'](arg1, arg2);
}

export function Mutes() {
  return window['go']['main']['App']['Mutes']();
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function OpenFaultlineLog() {
  return window['go']['main']['App']['OpenFaultlineLog']();
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenPath(arg1, arg2) {
  return window['go']['main']['App']['OpenPath'](arg1, arg2);
}

export function OpenRecent(arg1) {
  return window['go']['main']['App']['OpenRecent'](arg1);
}

export function PickEditor() {
  return window['go']['main']['App']['PickEditor']();
}

export function PickLogFile() {
  return window['go']['main']['App']['PickLogFile']();
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function RecentProjects() {
  return window['go']['main']['App']['RecentProjects']();
}

export function ReportError(arg1, arg2) {
  return window['go']['main']['App']['ReportError'](arg1, arg2);
}

export function SaveAndWatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAndWatch'](arg1, arg2, arg3);
}

export function SaveProjectConfig(arg1) {
  return window['go']['main']['App']['SaveProjectConfig'](arg1);
}

export function RevealExtension() {
  return window['go']['main']['App']['RevealExtension']();
}

export function Snooze(arg1, arg2) {
  return window['go']['main']['App']['Snooze'](arg1, arg2);
}

export function ExtensionDir() {
  return window['go']['main']['App']['ExtensionDir']();
}

export function Unmute(arg1, arg2) {
  return window['go']['main']['App']['Unmute'](arg1, arg2);
}
